# ali_sms
ALI_KEY_ID = 'xxx'
ALI_KEY_SECRET = 'xxx'
SMS_SIGN_NAME = '阿里云短信测试'
SMS_TEMPLATE_CODE = 'SMS_154950909'
SMS_CODE_EXPIRES = 300

# redis
REDIS_HOST = 'localhost'
REDIS_PORT = 6379
REDIS_PASSWORD = 'xxx'
